<?xml version="1.0" encoding="UTF-8"?>
<testrun name="WalletServiceTest" project="training" tests="14" started="14" failures="1" errors="1" ignored="0">
<testsuite name="ci.training.WalletServiceTest" time="0.094">
<testcase name="test_FundTransfer_NoAccount" classname="ci.training.WalletServiceTest" time="0.094"/>
<testcase name="test_showBalance_returnsNullForInvalidAccount" classname="ci.training.WalletServiceTest" time="0.0"/>
<testcase name="test_FundTransfer_NotEnoughMoney" classname="ci.training.WalletServiceTest" time="0.0">
<failure>java.lang.AssertionError: Expected exception: ci.training.exceptions.InsufficientBalanceException&#13;
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:32)&#13;
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)&#13;
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)&#13;
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)&#13;
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)&#13;
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)&#13;
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)&#13;
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)&#13;
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)&#13;
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)&#13;
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)&#13;
&#13;
</failure>
</testcase>
<testcase name="test_deposit_returnsNullForInvalidAccount" classname="ci.training.WalletServiceTest" time="0.0"/>
<testcase name="test_deposit_amountShouldNotBeLessThanZero" classname="ci.training.WalletServiceTest" time="0.0"/>
<testcase name="test_deposit_success" classname="ci.training.WalletServiceTest" time="0.0"/>
<testcase name="test_showBalance_throwsExceptionForIllegalArguments" classname="ci.training.WalletServiceTest" time="0.0"/>
<testcase name="test_showBalance_success" classname="ci.training.WalletServiceTest" time="0.0"/>
<testcase name="test_createWallet_success" classname="ci.training.WalletServiceTest" time="0.0"/>
<testcase name="test_withdraw_returnsNullForInvalidAccount" classname="ci.training.WalletServiceTest" time="0.0"/>
<testcase name="test_withdraw_insufficientBalance" classname="ci.training.WalletServiceTest" time="0.0"/>
<testcase name="test_withdraw_success" classname="ci.training.WalletServiceTest" time="0.0"/>
<testcase name="test_FundTransfer_Success" classname="ci.training.WalletServiceTest" time="0.0">
<error>java.lang.NullPointerException&#13;
	at ci.training.WalletServiceTest.test_FundTransfer_Success(WalletServiceTest.java:143)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#13;
	at java.lang.reflect.Method.invoke(Method.java:498)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)&#13;
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)&#13;
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)&#13;
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)&#13;
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)&#13;
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)&#13;
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)&#13;
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)&#13;
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)&#13;
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)&#13;
&#13;
</error>
</testcase>
<testcase name="test_createWallet_throwsExceptionForIlllegalArguments" classname="ci.training.WalletServiceTest" time="0.0"/>
</testsuite>
</testrun>
